/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

/**
 *
 * @author julian
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        imgRedSocial = new javax.swing.JLabel();
        tituloRedSocial = new javax.swing.JLabel();
        generoRedSocial = new javax.swing.JLabel();
        imgJobs = new javax.swing.JLabel();
        tituloJobs = new javax.swing.JLabel();
        generoJobs = new javax.swing.JLabel();
        imgCodigoEnigma = new javax.swing.JLabel();
        tituloCodigoEnigma = new javax.swing.JLabel();
        generoCodigoEnigma = new javax.swing.JLabel();
        imgAprenciesFueraLinea = new javax.swing.JLabel();
        tituloAprendicesFueraLinea = new javax.swing.JLabel();
        generoAprendicesFL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peliculas para programadores");

        panel.setLayout(new java.awt.GridBagLayout());

        imgRedSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/redSocial.jpeg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        panel.add(imgRedSocial, gridBagConstraints);

        tituloRedSocial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloRedSocial.setText("Título: Red Social");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        panel.add(tituloRedSocial, gridBagConstraints);

        generoRedSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generoRedSocial.setText("Género: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        panel.add(generoRedSocial, gridBagConstraints);

        imgJobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jobs.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        panel.add(imgJobs, gridBagConstraints);

        tituloJobs.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloJobs.setText("Título: Jobs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        panel.add(tituloJobs, gridBagConstraints);

        generoJobs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generoJobs.setText("Género: Cine biográfico - Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        panel.add(generoJobs, gridBagConstraints);

        imgCodigoEnigma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/codigoEnigma.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        panel.add(imgCodigoEnigma, gridBagConstraints);

        tituloCodigoEnigma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloCodigoEnigma.setText("Título: Código Enigma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        panel.add(tituloCodigoEnigma, gridBagConstraints);

        generoCodigoEnigma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generoCodigoEnigma.setText("Género: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        panel.add(generoCodigoEnigma, gridBagConstraints);

        imgAprenciesFueraLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aprendicesFueraFLinea.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        panel.add(imgAprenciesFueraLinea, gridBagConstraints);

        tituloAprendicesFueraLinea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloAprendicesFueraLinea.setText("Titulo: Aprencices Fuera de Linea");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        panel.add(tituloAprendicesFueraLinea, gridBagConstraints);
        tituloAprendicesFueraLinea.getAccessibleContext().setAccessibleName("Título: Aprencices Fuera de Linea");

        generoAprendicesFL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        generoAprendicesFL.setText("Género: Drama y Comedia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        panel.add(generoAprendicesFL, gridBagConstraints);

        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel generoAprendicesFL;
    private javax.swing.JLabel generoCodigoEnigma;
    private javax.swing.JLabel generoJobs;
    private javax.swing.JLabel generoRedSocial;
    private javax.swing.JLabel imgAprenciesFueraLinea;
    private javax.swing.JLabel imgCodigoEnigma;
    private javax.swing.JLabel imgJobs;
    private javax.swing.JLabel imgRedSocial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel tituloAprendicesFueraLinea;
    private javax.swing.JLabel tituloCodigoEnigma;
    private javax.swing.JLabel tituloJobs;
    private javax.swing.JLabel tituloRedSocial;
    // End of variables declaration//GEN-END:variables
}
