/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;

/**
 *
 * @author julian
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etqIngreso = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        etqUser = new javax.swing.JLabel();
        cajaUser = new javax.swing.JTextField();
        etqlPass = new javax.swing.JLabel();
        cajaClave = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        etqFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(735, 459));
        setMinimumSize(new java.awt.Dimension(735, 459));
        setUndecorated(true);

        panel.setMaximumSize(new java.awt.Dimension(735, 459));
        panel.setMinimumSize(new java.awt.Dimension(735, 459));
        panel.setPreferredSize(new java.awt.Dimension(735, 459));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etqIngreso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        etqIngreso.setForeground(new java.awt.Color(255, 255, 255));
        etqIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingreso.png"))); // NOI18N
        panel.add(etqIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 150, -1));

        etqUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etqUser.setForeground(new java.awt.Color(255, 255, 255));
        etqUser.setText("Usuario:");
        panel.add(etqUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        cajaUser.setBackground(new java.awt.Color(0, 0, 0));
        cajaUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cajaUser.setForeground(new java.awt.Color(255, 255, 255));
        panel.add(cajaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 160, 30));

        etqlPass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        etqlPass.setForeground(new java.awt.Color(255, 255, 255));
        etqlPass.setText("Clave:");
        panel.add(etqlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        cajaClave.setBackground(new java.awt.Color(0, 0, 0));
        cajaClave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cajaClave.setForeground(new java.awt.Color(255, 255, 255));
        cajaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaClaveActionPerformed(evt);
            }
        });
        panel.add(cajaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 160, 30));

        btnIniciar.setBackground(new java.awt.Color(0, 0, 0));
        btnIniciar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar sesion");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panel.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 160, -1));

        etqFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        panel.add(etqFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cajaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaClaveActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        String usuario = "Julian Morales";
        String password = "everJava";
        // Validar datos
        if (usuario.equals(cajaUser.getText())) {
            String psw = "";
            // El metodo getPassword devuelve un arreglo de caracteres y se pasa a String
            for (int i = 0; i < cajaClave.getPassword().length; i++) {
                psw += cajaClave.getPassword()[i];
            }
            if (password.equals(psw)) {
                JOptionPane.showMessageDialog(null, "Bienvenido: " + usuario);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario Incorrecto");
        }
    }//GEN-LAST:event_btnIniciarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPasswordField cajaClave;
    private javax.swing.JTextField cajaUser;
    private javax.swing.JLabel etqFondo;
    private javax.swing.JLabel etqIngreso;
    private javax.swing.JLabel etqUser;
    private javax.swing.JLabel etqlPass;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
